export const initialCards = [
  {
    id: "1",
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    link: "https://http2.mlstatic.com/D_NQ_NP_914124-MLA85253135136_062025-O.webp",
    description:
      "Cítrico fresco com toques de zimbro e alecrim. Evoca o verão mediterrâneo com leveza e descontração, ideal para o calor.",
    family: "Cítrico",
    occasion: "Casual",
    climate: "Calor",
    intensity: "Leve",
    role: "Papel na coleção ainda não definido. Em breve a inteligência do Aromatik vai analisar sua coleção e revelar o papel deste perfume.",
  },
  {
    id: "2",
    name: "Dior Homme Intense",
    brand: "Dior",
    link: "https://http2.mlstatic.com/D_NQ_NP_754743-MLA80116075781_102024-O.webp",
    description:
      "Íris empoado e aveludado com lavanda, âmbar e cedro. Sofisticado e sensual, com presença elegante e envolvente para ocasiões especiais.",
    family: "Floral",
    occasion: "Evento",
    climate: "Frio",
    intensity: "Intenso",
    role: "Papel na coleção ainda não definido. Em breve a inteligência do Aromatik vai analisar sua coleção e revelar o papel deste perfume.",
  },
  {
    id: "3",
    name: "Terre d'Hermès",
    brand: "Hermes",
    link: "https://leloynparfums.com.br/cdn/shop/files/70798_1.png?v=1769599428&width=1024",
    description:
      "Amadeirado seco e terroso, com sensação mineral e elegante. Presença madura, firme e discreta, mais racional do que expansiva.",
    family: "Amadeirado",
    occasion: "Dia",
    climate: "Ameno",
    intensity: "Moderado",
    role: "A assinatura diurna da coleção. Representa você no dia a dia com maturidade e elegância discreta. Presente e firme sem precisar gritar para ser notado por quem importa.",
  },
  {
    id: "4",
    name: "Bleu de Chanel",
    brand: "Chanel",
    link: "https://www.chanel.com/puls-img/1750768790390-onepdpeditopushdm974x1298px052xjpg_2596x1948.jpg",
    description:
      "Cítrico, aromático e amadeirado com fundo de incenso. Um clássico moderno de elegância discreta, equilibrado e extremamente versátil.",
    family: "Aromático",
    occasion: "Versátil",
    climate: "Ameno",
    intensity: "Moderado",
    role: "O coringa absoluto da coleção. Versátil, equilibrado e refinado, funciona do trabalho ao jantar sem errar nenhuma vez. Confiável e elegante em qualquer situação.",
  },
  {
    id: "5",
    name: "Bleu Noir",
    brand: "Narciso Rodriguez",
    link: "https://www.giraofertas.com.br/wp-content/uploads/2024/11/Narciso-Rodriguez-For-Him-Bleu-Noir-Parfum-Masculino-05.jpg",
    description:
      "Almiscarado e amadeirado com especiarias frias. Vetiver e cardamomo criam uma presença intensa e sedutora, densa e misteriosa.",
    family: "Almiscarado",
    occasion: "Noite",
    climate: "Frio",
    intensity: "Intenso",
    role: "Reservado para noites elegantes e ocasiões que exigem presença real. Sofisticado, misterioso e denso, é o perfume certo quando o momento pede impacto e memória.",
  },
];
